from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from google import genai
from google.genai import types
import base64
import os
import io
from PIL import Image as PILImage

app = FastAPI()

class ImageRequest(BaseModel):
    prompt: str
    aspect_ratio: str = "16:9"

@app.get("/health")
def health():
    """Health check endpoint"""
    api_key_set = bool(os.getenv("GOOGLE_API_KEY"))
    print(f"[Health Check] API Key: {'✓ SET' if api_key_set else '✗ NOT SET'}")
    return {
        "status": "ok",
        "api_key_set": api_key_set
    }

@app.post("/generate-image")
def generate_image(req: ImageRequest):
    """
    Generate educational image using Imagen 4.0
    
    FIXED: Properly extract image bytes using PIL
    """
    
    # Validation
    if not req.prompt or not req.prompt.strip():
        raise HTTPException(status_code=400, detail="Prompt cannot be empty")
    
    api_key = os.getenv("GOOGLE_API_KEY")
    if not api_key:
        print("[ERROR] GOOGLE_API_KEY not set in environment")
        raise HTTPException(
            status_code=500, 
            detail="GOOGLE_API_KEY environment variable not set"
        )

    try:
        print(f"[Imagen] Generating: {req.prompt[:70]}...")
        
        # Initialize client
        client = genai.Client(api_key=api_key)

        # Generate image with proper config
        result = client.models.generate_images(
            model="imagen-4.0-generate-001",
            prompt=req.prompt,
            config=types.GenerateImagesConfig(
                number_of_images=1,
                aspect_ratio=req.aspect_ratio,
                safety_filter_level="block_most",
                person_generation="allow_adult",
                negative_prompt="text overlay, words, letters, watermark, blurry, low quality"
            )
        )

        # Extract image
        if not result.generated_images or len(result.generated_images) == 0:
            print("[ERROR] No images returned from API")
            raise HTTPException(
                status_code=500, 
                detail="No images generated by API"
            )

        generated_image = result.generated_images[0]
        
        # CRITICAL FIX: Use the correct attribute to access image
        # The Image object has a _pil_image property that contains the PIL Image
        if hasattr(generated_image.image, '_pil_image'):
            pil_image = generated_image.image._pil_image
        elif hasattr(generated_image.image, 'image_bytes'):
            # Fallback: if image_bytes exists, use it directly
            image_bytes = generated_image.image.image_bytes
            base64_img = base64.b64encode(image_bytes).decode("utf-8")
            print(f"[Imagen] ✓ Success via image_bytes ({len(image_bytes)} bytes)")
            return {"image": base64_img}
        else:
            # Alternative: Try to get the PIL image directly
            pil_image = generated_image.image
        
        # Convert PIL Image to bytes
        img_byte_arr = io.BytesIO()
        pil_image.save(img_byte_arr, format='PNG', optimize=True, quality=95)
        image_bytes = img_byte_arr.getvalue()
        
        # Encode to base64
        base64_img = base64.b64encode(image_bytes).decode("utf-8")

        print(f"[Imagen] ✓ Success ({len(image_bytes)} bytes = {len(image_bytes)/1024:.1f}KB)")

        return {"image": base64_img}

    except HTTPException:
        raise
    except Exception as e:
        error_msg = str(e)
        print(f"[Imagen ERROR] {error_msg}")
        import traceback
        traceback.print_exc()
        
        raise HTTPException(
            status_code=500, 
            detail=f"Image generation failed: {error_msg}"
        )


if __name__ == "__main__":
    import uvicorn
    print("\n" + "="*50)
    print("🚀 Starting Imagen Service")
    print("="*50)
    print(f"API Key: {'✓ SET' if os.getenv('GOOGLE_API_KEY') else '✗ NOT SET'}")
    print("="*50 + "\n")
    uvicorn.run(app, host="0.0.0.0", port=8000)