from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from google import genai
from google.genai import types
import base64
import os
import io
from PIL import Image as PILImage

app = FastAPI()

class ImageRequest(BaseModel):
    prompt: str
    aspect_ratio: str = "16:9"

@app.get("/health")
def health():
    """Health check endpoint"""
    api_key_set = bool(os.getenv("GOOGLE_API_KEY"))
    print(f"[Health Check] API Key: {'✓ SET' if api_key_set else '✗ NOT SET'}")
    return {
        "status": "ok",
        "api_key_set": api_key_set
    }

@app.post("/generate-image")
def generate_image(req: ImageRequest):
    """
    Generate educational image using Imagen 4.0
    
    FIXED: Properly extract image bytes - handles multiple SDK versions
    """
    
    # Validation
    if not req.prompt or not req.prompt.strip():
        raise HTTPException(status_code=400, detail="Prompt cannot be empty")
    
    api_key = os.getenv("GOOGLE_API_KEY")
    if not api_key:
        print("[ERROR] GOOGLE_API_KEY not set in environment")
        raise HTTPException(
            status_code=500, 
            detail="GOOGLE_API_KEY environment variable not set"
        )

    try:
        print(f"[Imagen] Generating: {req.prompt[:70]}...")
        
        # Initialize client
        client = genai.Client(api_key=api_key)

        # Generate image
        result = client.models.generate_content(
            model="imagen-4.0-generate-001",
            contents=req.prompt,
        #    config={
        #        'number_of_images':1,
        #        'aspect_ratio':req.aspect_ratio,
        #        'safety_filter_level':"block_most",
        #        'person_generation':"allow_adult",
        #        'negative_prompt':"text overlay, words, letters, watermark, blurry, low quality"
        #    }
        )

        # Extract image
        if not result.generated_images or len(result.generated_images) == 0:
            print("[ERROR] No images returned from API")
            raise HTTPException(
                status_code=500, 
                detail="No images generated by API"
            )

        generated_image = result.generated_images[0]
        print(f"[Debug] Generated image type: {type(generated_image)}")
        print(f"[Debug] Image object type: {type(generated_image.image)}")
        print(f"[Debug] Image attributes: {dir(generated_image.image)}")
        
        # Try multiple methods to extract image bytes
        image_bytes = None
        
        # Method 1: Direct image_bytes attribute
        if hasattr(generated_image.image, 'image_bytes'):
            image_bytes = generated_image.image.image_bytes
            print(f"[Imagen] ✓ Method 1: image_bytes ({len(image_bytes)} bytes)")
        
        # Method 2: PIL Image object
        elif hasattr(generated_image.image, '_pil_image'):
            pil_image = generated_image.image._pil_image
            img_byte_arr = io.BytesIO()
            pil_image.save(img_byte_arr, format='PNG', optimize=True, quality=95)
            image_bytes = img_byte_arr.getvalue()
            print(f"[Imagen] ✓ Method 2: _pil_image ({len(image_bytes)} bytes)")
        
        # Method 3: Try to treat as PIL Image directly
        else:
            try:
                img_byte_arr = io.BytesIO()
                generated_image.image.save(img_byte_arr, format='PNG', optimize=True, quality=95)
                image_bytes = img_byte_arr.getvalue()
                print(f"[Imagen] ✓ Method 3: direct PIL save ({len(image_bytes)} bytes)")
            except Exception as e:
                print(f"[Imagen] Method 3 failed: {e}")
        
        if not image_bytes:
            raise HTTPException(
                status_code=500,
                detail="Could not extract image bytes from API response"
            )
        
        # Encode to base64
        base64_img = base64.b64encode(image_bytes).decode("utf-8")
        print(f"[Imagen] ✓ Final size: {len(image_bytes)/1024:.1f}KB (base64: {len(base64_img)/1024:.1f}KB)")

        return {"image": base64_img}

    except HTTPException:
        raise
    except Exception as e:
        error_msg = str(e)
        print(f"[Imagen ERROR] {error_msg}")
        import traceback
        traceback.print_exc()
        
        raise HTTPException(
            status_code=500, 
            detail=f"Image generation failed: {error_msg}"
        )


if __name__ == "__main__":
    import uvicorn
    print("\n" + "="*50)
    print("🚀 Starting Imagen Service")
    print("="*50)
    print(f"API Key: {'✓ SET' if os.getenv('GOOGLE_API_KEY') else '✗ NOT SET'}")
    print("="*50 + "\n")
    uvicorn.run(app, host="0.0.0.0", port=8000)